title: Chris Lorch
description: Chris' homepage on the world wide web.
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-125451449-1"
    anonymize_ip: false # default

theme: jekyll-theme-cayman