remote_theme: chrislorch/jekyll-material-theme
title: Chris Lorch
description: Chris' homepage on the world wide web.
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-67434859-5"
    anonymize_ip: false # default
